/**
 * Experience and education timeline data
 */

import { Briefcase, GraduationCap, Award, Shield, Code2, Rocket } from 'lucide-react';

export const EXPERIENCES = [
  {
    type: 'education',
    title: 'MSc Artificial Intelligence',
    organization: 'National College of Ireland, Dublin',
    period: 'Sep 2024 - Sep 2025',
    description: 'First Class Honours | 71.4% Overall Average | 3.1/4.0 GPA | 90 ECTS Credits',
    achievements: [
      'Programming for Artificial Intelligence: 79.1%',
      'Practicum/Thesis Project (DeepFake Detection): 77.6%',
      'AI Driven Decision Making: 76.8%',
      'Engineering and Evaluating AI: 70%',
      'Data Analytics for AI: 67.9%',
      'Machine Learning: 67.8%',
      'Also completed: Intelligent Agents, Process Automation, Data Governance & Ethics, Emerging AI Technologies',
    ],
    icon: GraduationCap,
    color: 'primary',
  },
  {
    type: 'work',
    title: 'Security Guard',
    organization: 'RFC Security Group · Full-time',
    period: 'Sep 2023 - Present · 2 yrs 7 mos',
    description: 'Role undertaken as part of a formal & legal employment pathway toward Stamp 4 residency in Ireland. A strategic & compliant choice aligned with long-term residency goals, while continuing to build a technical profile in software, cloud, and AI engineering in parallel.',
    achievements: [
      'Responsible for site security, access control, and incident response in live environments',
      'Operated under strict operational procedures requiring reliability, accountability, and situational awareness',
      'Acted as first point of response for escalations and safety-critical events',
      'Maintained clear communication with site management and external stakeholders',
    ],
    icon: Shield,
    color: 'accent',
    className: 'opacity-60',
  },
  {
    type: 'work',
    title: 'System Operations Engineer (Contractor)',
    organization: 'NDA Client (EU)',
    period: 'Sep 2022 - Oct 2025 · 3 yrs 2 mos',
    description: 'Independent SysOps/CloudOps engineer operating Microsoft-based environments end to end. Client details withheld under Non-Disclosure Agreement.',
    achievements: [
      'Manage and harden Entra ID (Azure AD), Intune, Azure, and Windows 365 Cloud PC',
      'Design and enforce Intune configuration & compliance policies and security baselines',
      'Implement Conditional Access & MFA (device trust and risk-/session-based controls)',
      'Automate operations with PowerShell (inventory, reporting, Autopilot, patch flows)',
      'Oversee VDI operations and optimize user experience and performance',
      'Proactive patch management and system health monitoring with root-cause analysis',
      'Configure Google Workspace policies and secure interop with Microsoft 365',
      'Produce runbooks, documentation, and SOPs focused on security and scalability',
    ],
    icon: Briefcase,
    color: 'primary',
  },
  {
    type: 'work',
    title: 'Junior Python Developer',
    organization: 'Art-In Systems, Turkey',
    period: 'Jun 2022 - Mar 2023 · 10 mos',
    description: 'Developed enterprise dashboards and data processing solutions for 100+ customers using Django and Oracle DB.',
    achievements: [
      'Built comprehensive dashboard control panels for 100+ customers and administrators',
      'Enhanced data processing efficiency by 40% using Selenium, Beautiful Soup, and Pandas',
      'Optimized MySQL queries for improved data retrieval and management',
      'Implemented automated data extraction and ETL pipelines',
      'Conducted exploratory data analysis for business decision-making',
      'Worked with Oracle DB and PostgreSQL for secure data storage',
    ],
    icon: Code2,
    color: 'secondary',
  },
  {
    type: 'work',
    title: 'Junior Back End Developer (Internship)',
    organization: 'Atolla, Turkey',
    period: 'Feb 2022 - May 2022 · 4 mos',
    description: 'Optimized backend performance using multithreading and implemented ETL processes with focus on scalability.',
    achievements: [
      'Reduced page loading times by 45% through multithreading optimization',
      'Gained expertise in Struts Framework and MVC architecture',
      'Implemented security measures and data protection protocols',
      'Collaborated with team of 5 to deliver solutions resulting in 1,000+ new subscribers',
      'Developed and executed ETL data processing scripts',
      'Conducted statistical analysis on user behavior patterns',
    ],
    icon: Briefcase,
    color: 'primary',
  },
  {
    type: 'work',
    title: 'Start-up Owner',
    organization: 'FlyBee Delivery',
    period: '2021 - 2022 · 1 yr',
    description: 'Founded and led aviation delivery start-up focusing on UAV courier solutions. Project suspended due to regulatory challenges under Turkish aviation laws.',
    achievements: [
      'Developed robust business model tailored to aviation delivery industry',
      'Built and led diverse team fostering innovation culture',
      'Implemented TensorFlow, AI, and ML for operational efficiency',
      'Conducted financial analysis and account management',
      'Navigated legal and regulatory challenges in aviation sector',
      'Obtained IHA-1 Drone Pilot License for operational expertise',
    ],
    icon: Rocket,
    color: 'accent',
  },
  {
    type: 'education',
    title: 'BSc Software Engineering',
    organization: 'National Technical University of Ukraine (KPI)',
    period: 'Sep 2019 - Jun 2023',
    description: 'Graduated with exceptional academic performance. Member of DSC KPI (Developer Student Club).',
    achievements: [
      'Achieved outstanding 93.4/100 grade (3.96/4.0 GPA)',
      'Active member of Developer Student Club (DSC KPI)',
      'Built strong foundation in algorithms and data structures',
      'Developed expertise in OOP, software design patterns, and architecture',
      'Gained proficiency in Python, C++, Django, Flask, AWS, and R',
    ],
    icon: Award,
    color: 'secondary',
  },
] as const;

export const ACHIEVEMENTS_BAR = [
  { text: 'First Class Honours · MSc AI', icon: GraduationCap },
  { text: 'Published Researcher · Springer CCIS 2025', icon: Award },
  { text: '3+ Years Enterprise Engineering', icon: Briefcase },
  { text: 'Startup Founder · AI/Drone Tech', icon: Rocket },
] as const;
